name: notify
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'bin/**'
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Send a Slack notification
        uses: 8398a7/action-slack@v3
        with:
          text: flywheel-standard was updated.
          status: ${{job.status}}
          author_name: flywheel-standard
          fields: author,message
          channel: '#eng-general'
        env:
          SLACK_WEBHOOK_URL: ${{secrets.FWBOT_SLACK_WEBHOOK_URL}}
