name: upload
on:
  push:
    branches: [master]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # flywheel-jp/mouseion/upload internally uses gsutil and gsutil
      # skips symlink directory "public/docs"
      - uses: flywheel-jp/mouseion/upload@master
        with:
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          source: public
      # ... so upload "public/docs" directory.
      - uses: flywheel-jp/mouseion/upload@master
        with:
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          namespace: flywheel-standard/docs
          source: public/docs
